### ISSUE TITLE
tlsVersion field is inconsistent with TLS 1.3

### ISSUE THREAD

**Issue by davidben** [EFForg/webrequest-tlsinfo-api#1]
The proposed version reporting scheme would not work for how we represent TLS 1.3. We do not store the protocol version but a higher-level enum. In particular, TLS 1.3 draft versions are just stored as TLS 1.3. (It is unclear if the draft version values are intended to be long-term stable allocations, so exposing them seems especially unwise.) QUIC is also represented in this enum.

It is also not documented what this field and the cipher suite suite field do for QUIC. (We map QUIC parameters to a vaguely similar TLS cipher suite.)

**Comment by alex** [comment]
Splitting up `{major, minor}` seems fancier than what's necessary. Just an `enum` seems easiest. (Still need to figure out what to do about draft versions and QUIC, but that's a different matter)

**Comment by davidben** [comment]
We map draft versions to TLS 1.3. Changing that just for an extensions API does not make sense.

**Comment by alex** [comment]
👍 I don't have a use case that cares about TLS draft versions. Do you @rolandshoemaker?

**Comment by rolandshoemaker** [comment]
Works for me. I think(?) there is work on a QUIC protocol revision, is there any plan in the future to expose the QUIC protocol version (if that is even going to be a thing)? In that case it might make sense to just rename the field `protocolVersion` which would reflect the version of whatever is set in `protocol`...

**Comment by davidben** [comment]
QUIC gets revised pretty constantly, yes. I do not know of any plans to expose the QUIC protocol version. Without a need for it, we should not expose it.

Note that, in the future, QUIC will be using the TLS handshake anyway, at which point we may wish to report TLS version independent of QUIC. Unclear. This sort of thing is why we need to default to not exposing things. The less time we have to waste on picking things like this and worrying about breaking things, the more time we can spend on actually improving the web.

**Comment by rolandshoemaker** [comment]
:+1:
