### ISSUE TITLE
Remove embededOCSP and embededSCT

### ISSUE THREAD

**Issue by davidben** [EFForg/webrequest-tlsinfo-api#2]
These should not be in the first iteration and require more careful thought as to what fields are actually worth retaining (increased memory use) on the response. Right now we do not expose the full OCSP response out of //net. The SCT we sort of do by way of exposing the SCTs with their origin.

We should not increase memory usage of the browser for all users purely for the small fraction who would install an extension that would use these. Even for things we do happen to retain right now, exposing any field to the extensions system means we are can no longer change this for future improvements, so there is a high bar to be met for each large field.

**Comment by rolandshoemaker** [comment]
:+1:, seems fair.
