### ISSUE TITLE
How should QUIC parameters be exposed

### ISSUE THREAD

**Issue by rolandshoemaker** [EFForg/webrequest-tlsinfo-api#3]
Internally Chromium seems to format the QUIC crypto parameters as somewhat similar TLS cipher suite which would seem slightly misleading to expose. Perhaps if `protocol` is QUIC it would be best to just omit this field?

**Comment by rolandshoemaker** [comment]
(I think the best solution here is to just not include this data `¯\_(ツ)_/¯`)

**Comment by alex** [comment]
My primary interest is in the bad crypto, so I don't care if I don't have data on the good stuff :D

**Comment by alex** [comment]
Can this be closed following 1a382d73ed5416c7aeb2a45808cc4ea850aaf951?

**Comment by rolandshoemaker** [comment]
> Can this be closed following 1a382d7?

Yes I think so, we could quibble about exposing other QUIC specific information but I think that is probably a waste of time considering how infrequent its use is compared to TLS.
